# Site
repository: abhiraichuri/abhiraichuri.github.io
favicon: images/favicon.ico

# Personal info
name: Abhilash Raichur
title: Senior Cloud Engineer at AWS
email: abhiraichuri@gmail.com
website: abhiraichuri.xyz

# Social links
#twitter_username: sproogen
#github_username:  sproogen
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
linkedin_username: abhiraichuri
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/abhi.jpg
about_content: |
  Hi, my name is Abhilash Raichur, I'm a passionate cloud solutions developer with over 8 years experience.
  I am currently working for the Amazon Web Servives(AWS) as a Senior Cloud Engineer.

  I enjoy making AWS based cloud solutions for different use cases. I work with Enterprise customers assisting them with design, development,
  support and provide proactive advice through all phases of the implementation life cycle. I am always passionate about learning new
  technologies and doing Proof of concepts(POC's) to understand the limitations. The things that I currently have the most experience working with are:
  <mark>AWS Services</mark>,
  <mark>.Net</mark>,
  <mark>Java</mark>,
  <mark>Python</mark>,
  <mark>MySQL</mark>,
  <mark>Amazon DynamoDB</mark>,
  <mark>git</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: When I'm Not Programming
more_content: |
  When I'm not at my desk I am very active and spend most of my time outdoors. I do a lot a sports such as
  cricket, tennis, badminton and soccer as well as trying to make time for things like
  rock climbing and hiking. Since my time at University I have become a very keen to hiking and exploring
  new places. I also try to make time to learn new hobbies and my recent one being Bartending. 
  Note: They do not teach juggling the glasses/bottles at Bartending school. 

  I'm interested in photography as I like to be creative, this is mainly through sport but
  I enjoy landscape and abstract photography too. 

  Finally during the rest of my free time you will either find me working on my travel blogs, reading news, gym or making plans for future travel.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
